controller_manager_ns: ''
controller_list:
  - name: /ariac/arm1/arm
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    default: true
    joints:
	    - linear_arm_actuator_joint
	    - shoulder_pan_joint
	    - shoulder_lift_joint
	    - elbow_joint
	    - wrist_1_joint
	    - wrist_2_joint
	    - wrist_3_joint
